name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://calbaptist.edu/financial-aid/undergraduate/tuition-and-fees > tuition-and-fees.html
        curl https://calbaptist.edu/programs/bachelor-of-science-mechanical-engineering/courses > bachelor-of-science-mechanical-engineering-courses.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
